const ROLES=[['北国三皇子','北国','野心家，直面夺嫡血腥'],['北国军师之女','北国','智谋担当，以棋局定天下'],['北国边关守将','北国','武力担当，手握兵符'],['北国郡主','北国','调和者，游走权贵之间'],['南国长公主','南国','核心人物，面临联姻压力'],['南国状元郎','南国','清流代表，以笔为剑'],['南国将军之子','南国','主战派，渴望建功'],['南国富商之子','南国','经济支柱，善用财货'],['西域神秘商人','中立','倒卖情报与军火'],['前朝遗孤','中立','身世坎坷的复国者'],['江湖盟主之子','中立','草莽英雄，以武犯禁'],['天机阁传人','中立','预言家，知晓部分未来']];
const NPCS=[['萧玦','北国九皇子','深沉内敛，表面儒雅，实则极善隐忍与布局。','谋略 S｜剑术 A｜驭下 S'],['慕容璃','南国长公主','聪慧坚韧，心系百姓，渴望掌握自己的命运。','琴棋 S｜外交 A｜医术 B'],['贺兰辞','北国大将军','豪迈重义，谁能让他心服，他便忠于谁。','骑射 S｜兵法 S｜统率 S'],['苏清月','天下第一舞姬','八面玲珑的密探首领，只为寻找灭门真相。','舞蹈 S｜易容 A｜情报 S'],['陆珩','南国首富之子','精明圆滑，乱世中只求自保，投资眼光极准。','经商 S｜算术 S｜鉴宝 A'],['赵钦','北国锦衣卫指挥使','阴鸷冷血，只认令牌不认人。','审讯 S｜追踪 S｜暗杀 A'],['顾晚棠','神医谷传人','清冷孤傲，对疑难杂症有近乎偏执的好奇。','医术 S｜毒术 A｜药理 S'],['李承泽','南国太子','温文仁厚，渴望和平，却易受朝臣影响。','仁政 A｜书法 S｜骑射 C'],['阿史那云','草原部落质子','野性难驯，忍辱负重，胸中藏着复国与复仇。','野战 S｜驯鹰 A｜草原知识 S'],['柳如烟','醉仙楼老板娘','泼辣精明，出得起价便没有买不到的消息。','厨艺 S｜交际 S｜窃听 A'],['百里辰','神秘江湖剑客','冷漠孤僻，拿钱办事，却不伤老弱妇孺。','剑术 S｜轻功 S｜追踪 A'],['上官锦','御史之女','天真浪漫，嫉恶如仇，敢在朝堂直谏。','文采 S｜辩论 A｜绘画 S']];
const q=(target,text,choices)=>({target,text,choices});
const BANK={
 power:[
 q('萧玦','三皇子深夜密访，许诺以半壁江山换你一句支持。',['直言效忠，愿为殿下谋划。','婉言谢绝，只求明哲保身。','虚与委蛇，先套取情报。']),q('贺兰辞','沧澜关传来军报，敌军已至城下，皇帝问谁可挂帅。',['荐贺兰辞挂帅，以能者当先。','亲自请缨，立下军令状。','荐政敌领兵，借刀除患。']),q('李承泽','你发现太子暗中资助北国难民，朝中已有人要以通敌论罪。',['替他遮掩，并安排安全粮道。','以此要挟，换取官位。','公开揭露，坐看储位易主。']),q('赵钦','赵钦持令搜查你的府邸，态度强硬。',['开门配合，清者自清。','闭府抗命，誓不受辱。','备下证据，再请他入府。']),q('苏清月','苏清月递来密信，称朝中有人欲刺杀和亲使臣。',['帮她布下反局，等刺客现身。','将信焚毁，不愿卷入。','转交两国使臣，换取人情。']),q('阿史那云','质子阿史那云求你放他回草原探病。',['冒险伪造文书，助他离城。','严词拒绝，以免连累自己。','提出条件，要他日后效命。']),q('上官锦','上官锦准备在朝堂弹劾贪官，却被父亲禁足。',['替她递上奏章，承担后果。','劝她忍耐，待风头过去。','将奏章卖给政敌。']),q('慕容璃','和亲诏书将至，慕容璃问你如何保全南国。',['建议她争取谈判主导权。','劝她顺从，以一人换太平。','安排她秘密出逃。']),q('贺兰辞','贺兰辞违抗军令追击敌军，正等你一句裁断。',['替他据理力争，保住兵权。','按军法处置，以正朝纲。','劝他交出兵符避祸。']),q('萧玦','夺嫡双方同时邀你赴宴，皆暗藏杀机。',['只赴萧玦之宴，明示立场。','两边都不去，称病自保。','分别送礼，让双方猜疑。']),q('赵钦','赵钦让你辨认一名疑似前朝余孽的囚犯。',['坚持查清证据再定罪。','顺着他的意思指认。','暗中放走囚犯。']),q('李承泽','太子犹豫是否削减世家兵权。',['支持渐进改革，先安民心。','劝他立刻收兵权。','建议搁置，避免树敌。']),q('苏清月','苏清月发现你的盟友与敌国互通书信。',['请她继续追查，收集铁证。','立刻质问盟友。','装作不知，反向利用。']),q('阿史那云','草原部落使者提出以战马换回阿史那云。',['促成交易，给他一线生机。','拒绝交易，防其归国复仇。','要求部落先交出边境情报。']),q('上官锦','御史台要你在一桩冤案上签字。',['与上官锦一同复查卷宗。','签字保全自身。','拖延时间，等局势变化。']),q('慕容璃','慕容璃愿以私印换取百姓撤离时间。',['助她调动船只，先救百姓。','劝她留住印信。','拿印信同朝臣谈条件。']),q('萧玦','萧玦把半枚虎符交给你保管。',['收下虎符，替他守住秘密。','婉拒，避免卷入党争。','转交贺兰辞求证。']),q('贺兰辞','军中粮草被截，贺兰辞欲劫掠商队。',['劝他向富商借粮，立下欠据。','支持劫粮，战事为先。','建议撤军固守。']),q('赵钦','赵钦请你参与一场秘密审讯。',['旁听并阻止酷刑。','协助审讯，尽快得口供。','借机与囚犯私下交谈。']),q('李承泽','李承泽问你，和平若需割地是否值得。',['说民生比疆土更要紧。','说寸土不让，宁战不屈。','建议先以互市换取缓冲。'])],
 love:[
 q('慕容璃','宫宴之上，慕容璃琴弦忽断，场面尴尬。',['献上自己的琴，称公主才情无双。','说琴弦为春风所断，是祥瑞。','静坐不语，等旁人解围。']),q('顾晚棠','顾晚棠遇到病危乞儿，却要赶去给皇子诊病。',['劝她先救乞儿，人命不分贵贱。','将乞儿抬往皇子府一并医治。','赠银两，请旁人照料。']),q('柳如烟','柳如烟给了你假消息，令你折损颇多。',['一笑置之，仍请她饮酒。','砸了醉仙楼，要她赔偿。','暗中查证，等她拿出真情报。']),q('百里辰','百里辰在雨夜受伤，却不愿暴露行踪。',['带他到安全处疗伤。','报官换取赏银。','留药后离开，不多追问。']),q('上官锦','上官锦因直谏受辱，独自站在宫门外。',['陪她等到天亮，听她说完。','劝她低头向权贵道歉。','替她写一封更锋利的奏疏。']),q('阿史那云','阿史那云的驯鹰飞走，神色罕见地慌乱。',['陪他去城外寻鹰。','笑他为一只鸟失态。','托人寻找，自己留在城中。']),q('李承泽','李承泽邀你在书房品茶，坦言自己害怕辜负百姓。',['告诉他软弱不是罪，逃避才是。','劝他做一个更强硬的储君。','沉默听完，替他守住秘密。']),q('苏清月','苏清月在舞后独坐灯下，提及灭门旧案。',['承诺替她查访旧案。','劝她放下仇恨。','用旧案换取她的情报。']),q('贺兰辞','贺兰辞醉后谈起战死的旧部。',['与他共饮，听他逐一念名。','劝他忘记过去。','提醒他军中不可失态。']),q('陆珩','陆珩送来一箱稀罕珠宝，称只是朋友之礼。',['只留一件小物，其余退回。','全部收下，回赠古玩。','婉拒，怕惹人议论。']),q('赵钦','赵钦默默替你挡下一支暗箭。',['郑重道谢，并替他包扎。','追问他为何相救。','假装无事，不欠人情。']),q('慕容璃','慕容璃想看金陵夜市，却无法随意出宫。',['设法安排便衣同游。','劝她以国事为重。','带回夜市的小食与故事。']),q('顾晚棠','顾晚棠制出新药，却不敢在人身上试用。',['愿意先试药，替她担险。','劝她先用在死囚身上。','帮她找来医书佐证。']),q('柳如烟','柳如烟生日无人知晓，只煮了一碗长寿面。',['带酒登门，为她唱一支小调。','送她一匣金锭。','假装路过，坐下吃面。']),q('百里辰','百里辰要离开金陵，未说明去处。',['赠他一枚可回信的玉佩。','追问他的真实身份。','只说一路保重。']),q('上官锦','上官锦画了一幅你的画像，却怕你取笑。',['认真题字，珍藏起来。','笑称画得不像。','请她再画一幅山河。']),q('阿史那云','阿史那云收到部落覆灭的假消息。',['陪他辨别消息真伪。','劝他不要冲动回草原。','替他安排一场祭奠。']),q('李承泽','李承泽听闻流言，说你与敌国使者来往。',['当面解释，给他看全部书信。','不作解释，任由他猜。','请他亲自去问使者。']),q('苏清月','苏清月要以身作饵引出仇人。',['陪她布置退路。','劝她放弃行动。','暗中通知赵钦。']),q('贺兰辞','贺兰辞邀你雪夜煮酒，问何为英雄。',['说守住想守的人便是英雄。','说成王败寇，胜者为雄。','笑而不答，与他碰杯。'])],
 money:[
 q('陆珩','陆珩邀你合做军火生意，利润惊人，却违背停战盟约。',['拒绝并劝他莫发国难财。','富贵险中求，立刻入股。','佯装答应，暗中举报。']),q('阿史那云','天京饥荒，你的粮仓尚存过冬之粮。',['开仓放粮，救济百姓。','高价售粮，趁机获利。','半数赈济，半数献给朝廷。']),q('慕容璃','西域汗血宝马亟待入关，独缺一纸文牒。',['借公主名义通关，取合理佣金。','买通守将，夜里偷运。','放弃此单，守住底线。']),q('柳如烟','柳如烟得知一处盐井消息，邀你共同买下。',['出资但约定惠及当地百姓。','独占消息，抢先买下。','拒绝投资，怕惹麻烦。']),q('贺兰辞','贺兰辞军中缺棉衣，商户趁机抬价。',['压下价格，先保将士御寒。','按高价买下，换商户支持。','建议军中自行缝制。']),q('李承泽','太子想修水渠，国库却只够一项大工程。',['支持修渠，先解百姓之困。','建议修行宫以固威仪。','让富商认捐，再由朝廷补贴。']),q('顾晚棠','顾晚棠发现一种稀有药材可救疫病，也可制成奇毒。',['资助她建立药圃，公开救治。','高价囤货，待价而沽。','请她把配方交给朝廷。']),q('陆珩','陆珩的船队被扣在关外，急需担保人。',['替他担保，并核查货单。','趁机压低他的股份。','劝他舍弃货物保人。']),q('赵钦','赵钦查出一批赈灾银去向不明。',['协助追账，归还灾民。','建议先填补账面漏洞。','拿线索交换自己的利益。']),q('上官锦','上官锦提议设立女子书院，却无人愿意出资。',['捐资并请她主持。','说乱世不宜办学。','建议先开小规模夜学。']),q('阿史那云','草原商队带来羊毛与马匹，要求用铁器交换。',['谈成有限贸易，互留余地。','囤积铁器，高价交换。','拒绝交易，防其壮大。']),q('苏清月','苏清月需要一笔钱赎出被卖的线人。',['立刻出钱，先救人。','要求她先交出情报。','转请柳如烟筹款。']),q('慕容璃','慕容璃想以宫中旧物换粮赈灾。',['帮她找可靠商号变卖。','劝她保留体面。','拿旧物做一次投机。']),q('贺兰辞','贺兰辞提议用战马抵押向商人借粮。',['替他谈低利钱，立下军约。','同意高息借粮，先过难关。','拒绝借贷，要求撤军。']),q('柳如烟','醉仙楼将被地痞勒索保护费。',['出面保护她的生意。','建议她交钱息事宁人。','借机入股醉仙楼。']),q('李承泽','太子问你该减免赋税还是增兵备战。',['建议先减免灾区赋税。','建议先扩军备战。','建议向富户征特别税。']),q('顾晚棠','顾晚棠要免费施药，药铺掌柜担心亏本。',['补贴药铺，免费施药。','劝她改为低价售卖。','让掌柜独自承担。']),q('陆珩','陆珩请你评估一条绕开关税的秘密商道。',['劝他走正道，争取减税。','投资商道，共担风险。','把商道卖给赵钦。']),q('上官锦','上官锦查到官员侵吞书院善款。',['替她追回善款并公开账目。','劝她私下和解。','用账本换取政治支持。']),q('赵钦','赵钦查封一批走私货，问你如何处置。',['拍卖货物，所得赈灾。','低价买下，自己转卖。','全部销毁，以儆效尤。'])]
};
const NPC_SKILL={
 '萧玦':{power:20,love:12,money:14},'慕容璃':{power:10,love:22,money:15},'贺兰辞':{power:22,love:16,money:10},'苏清月':{power:19,love:17,money:12},'陆珩':{power:12,love:13,money:22},'赵钦':{power:20,love:8,money:13},'顾晚棠':{power:8,love:20,money:16},'李承泽':{power:15,love:19,money:14},'阿史那云':{power:17,love:14,money:15},'柳如烟':{power:14,love:18,money:19},'百里辰':{power:16,love:13,money:11},'上官锦':{power:15,love:18,money:13}
};
const TASK_MATCH={
 power:[['萧玦','赵钦'],['苏清月','赵钦'],['慕容璃','李承泽'],['贺兰辞','上官锦'],['苏清月','萧玦'],['贺兰辞','赵钦'],['慕容璃','苏清月'],['上官锦','李承泽'],['赵钦','苏清月'],['萧玦','贺兰辞'],['贺兰辞','阿史那云'],['赵钦','萧玦'],['萧玦','上官锦'],['苏清月','赵钦'],['贺兰辞','李承泽'],['慕容璃','李承泽'],['赵钦','苏清月'],['上官锦','李承泽'],['萧玦','贺兰辞'],['贺兰辞','慕容璃']],
 love:[['顾晚棠','慕容璃'],['李承泽','上官锦'],['柳如烟','苏清月'],['百里辰','顾晚棠'],['上官锦','慕容璃'],['阿史那云','贺兰辞'],['李承泽','慕容璃'],['苏清月','柳如烟'],['贺兰辞','百里辰'],['陆珩','柳如烟'],['赵钦','百里辰'],['慕容璃','柳如烟'],['顾晚棠','李承泽'],['柳如烟','上官锦'],['百里辰','苏清月'],['上官锦','慕容璃'],['阿史那云','顾晚棠'],['贺兰辞','赵钦'],['李承泽','苏清月'],['慕容璃','贺兰辞']],
 money:[['陆珩','柳如烟'],['阿史那云','李承泽'],['陆珩','慕容璃'],['柳如烟','陆珩'],['贺兰辞','陆珩'],['李承泽','陆珩'],['顾晚棠','陆珩'],['陆珩','柳如烟'],['赵钦','柳如烟'],['上官锦','陆珩'],['阿史那云','陆珩'],['苏清月','柳如烟'],['慕容璃','陆珩'],['贺兰辞','陆珩'],['柳如烟','陆珩'],['李承泽','上官锦'],['顾晚棠','陆珩'],['上官锦','顾晚棠'],['柳如烟','陆珩'],['赵钦','陆珩']]
};
const OPTION_BANK={
 power:[
 ['请{n}在朝会上主陈利害，以其专长压住反对声。','让{n}以私人身份探听各方口风，再决定立场。','托{n}在城外布下暗哨，先保住退路。'],
 ['请{n}拆解密信中的暗语，找出幕后之人。','让{n}带着你的条件去试探对手底线。','请{n}先封存消息，避免引发朝野恐慌。'],
 ['请{n}主持临时会谈，以互市利益换取停火。','让{n}私下接触对方使者，探明真实诉求。','请{n}调集可信人手，防备谈判破裂。'],
 ['请{n}核查谣言源头，并公布可验证的证据。','让{n}安抚各方势力，暂缓冲突升级。','请{n}追查散布者，切断消息链条。'],
 ['请{n}复盘盟友的行踪，从细节找出破绽。','让{n}当面询问盟友，给对方解释机会。','请{n}布置反制方案，假意相信后再收网。'],
 ['请{n}比较军令与民情，拟定折中的执行方案。','让{n}向上请示，为你争取缓冲时间。','请{n}先执行最安全的部分，保住人手。'],
 ['请{n}评估交易中的政治代价，再提出条件。','让{n}借谈判拖延时间，等待援手。','请{n}暗中核验对方筹码，防止受骗。'],
 ['请{n}整理自证材料，在朝堂上逐条回应。','让{n}寻找愿意作证的旧部，稳住声望。','请{n}反查弹劾者的动机，把被动变主动。'],
 ['请{n}重审旧案卷宗，先求真相再论站队。','让{n}保护关键证人，避免证词被改。','请{n}以卷宗为饵，引幕后人现身。'],
 ['请{n}判断城门内外的风险，安排接应路线。','让{n}带人出城营救，速战速决。','请{n}留守城中，防备有人调虎离山。']
 ],
 love:[
 ['请{n}陪你坐到雨停，慢慢说出彼此心事。','让{n}替你送去一盏灯和一句问候。','请{n}先查明对方烦忧的缘由，再决定如何靠近。'],
 ['请{n}留在灯下倾听，不急着给出答案。','让{n}准备一份旧物，替你表达理解。','请{n}邀请对方散步，以轻松话题化解沉默。'],
 ['请{n}与当事人当面澄清流言，守住信任。','让{n}暂不辩解，先从源头查出谣言。','请{n}替你传话，给彼此冷静的余地。'],
 ['请{n}比对书信笔迹，找出误会的根源。','让{n}陪你赴约，亲口问清旧事。','请{n}替你保守秘密，不让伤口被旁人窥见。'],
 ['请{n}先救下眼前的人，再谈代价与责任。','让{n}安排稳妥后援，减少无谓牺牲。','请{n}劝对方量力而行，别把自己也赔进去。'],
 ['请{n}分出御寒物资，与大家共渡难关。','让{n}辨认风雪路线，带人尽快离开。','请{n}留在原地生火守夜，安定人心。'],
 ['请{n}陪对方整理旧物，让往事有个归处。','让{n}查访旧物来历，找回缺失的故事。','请{n}把旧物暂时收好，等对方愿意再谈。'],
 ['请{n}公开替对方说话，不让委屈被掩盖。','让{n}私下安慰，先护住对方的体面。','请{n}寻找合适时机，让误会自然澄清。'],
 ['请{n}送行并约定归期，把不舍说出口。','让{n}准备一件护身之物，替你留个念想。','请{n}只在远处守望，尊重对方的选择。'],
 ['请{n}安排一次坦诚相见，给双方解释机会。','让{n}先分别倾听两边的说法。','请{n}用一件共同经历过的事唤回信任。']
 ],
 money:[
 ['请{n}先核算粮价与存量，制定平价方案。','让{n}联络商户共同压价，保障民生。','请{n}设立赈济点，优先救助最急迫的人。'],
 ['请{n}勘验新商路的关隘与风险，再谈利润。','让{n}拟定公开契约，明确各方责任。','请{n}安排可靠人手押运，先保货与人。'],
 ['请{n}逐页核对账册，追查银两去向。','让{n}安抚受影响的商户，避免挤兑。','请{n}先补足灾款，再追究失职之人。'],
 ['请{n}评估出资条件，拒绝伤害百姓的条款。','让{n}分拆项目，引入多方小额资助。','请{n}准备备选资金，避免受制于单一商人。'],
 ['请{n}统筹运输路线，优先把物资送到边关。','让{n}与沿途商队谈互助，分担风险。','请{n}核验军需清单，避免中饱私囊。'],
 ['请{n}查验货单与扣押理由，依法交涉。','让{n}筹集担保金，先把人和货带回。','请{n}另寻替代货源，降低对单一商路依赖。'],
 ['请{n}规划集会摊位与税收，让小商贩也有位置。','让{n}建立公示账目，防止利益独占。','请{n}安排护卫与救火队，先保证集会安全。'],
 ['请{n}勘察矿产归属，提出长期保护方案。','让{n}协调各方分成，避免械斗。','请{n}先封存矿区，等证据齐备再开采。'],
 ['请{n}统计受灾商铺，制定低息周转方案。','让{n}组织工匠互助，尽快恢复工坊。','请{n}从富户筹得善款，优先救急。'],
 ['请{n}测算税令对百姓的影响，提出减负建议。','让{n}查清国库缺口，避免盲目加税。','请{n}设计分级税制，让富户多担一份。']
 ]
};
const EVENT_DETAILS={
 power:['御前侍卫已封住偏门，半个时辰内必须给出答复。','密信的火漆印来自本不该出现的人。','窗外使团侍卫正握紧刀柄，厅内无人敢先开口。','谣言已传到粮铺，若不处置，明日必会成乱。','盟友的随从在巷口留下了可疑脚印。','军令上的印章无误，却与边关实情完全相反。','对方承诺的利益很大，但代价没有写在纸上。','弹劾奏章已递到御前，只等你一句辩白。','卷宗边角有新墨，显然有人刚刚改动过。','城外火把渐近，留给众人的时间不多。','两军之间只有一条冻河，先动的人将失去主动。','令牌背面刻着一个被废除多年的旧印。','宴席上的每一句客套，都像在替下一场风暴探路。','刺客用的兵器来自军库，说明局内另有局。','争执声传出殿外，百官都在等你的取舍。','盟约的最后一日，边关忽然升起狼烟。','调兵文书若是真的，京城今晚就会失守。','新政告示刚贴出，便有人在街头煽动聚众。','旧友的信里只有一句：今夜之后，便是敌我。','密报称城防空隙只会维持到天明。'],
 love:['檐下雨声急促，对方几次欲言又止。','灯花爆了一声，满室热闹反倒衬得身影孤单。','流言已传遍驿馆，沉默也会被解作默认。','信纸被反复折叠，字迹已有些模糊。','周围的人都在观望，没人愿意先伸手。','风雪遮住了归路，火堆旁只剩下彼此。','旧物上有熟悉的香气，像把人拉回从前。','众目睽睽之下，那份难堪无法轻易掩去。','船马上就要离岸，错过便不知何时再见。','一句无心之语，已在两人间留下裂痕。','药炉未熄，对方却先问起你的安危。','人潮声鼎沸，转眼便失去了踪影。','你这才知道，那些风波原来都被人悄悄挡下。','月色很淡，正适合说出平日不敢说的话。','门外脚步声停了又走，谁都不愿先回头。','礼物没有署名，却分明是精心挑选过的。','故乡的消息真假难辨，最怕的是希望落空。','箭雨将至，信任比任何承诺都更快抵达。','承诺与责任压在同一张案上，谁都无法两全。','战事暂歇，错过的解释终于有了出口。'],
 money:['米行已排起长队，争执声惊动了巡城兵。','商路地图上有一处空白，谁也不知那里藏着什么。','账册的数字彼此矛盾，负责的人已经失踪。','出资人带着护卫而来，显然不只想做生意。','车队被困在山道，棉衣送迟一日便会冻死更多人。','货物在关外受潮，船主正催你立刻决定。','集会一旦开市，消息与银钱都会流向最快的人。','矿区附近已聚集两拨人，冲突一触即发。','工匠围在停工的坊门前，家中已无余粮。','粮仓钥匙就在眼前，但动用它意味着承担罪名。','河道淤塞，雨季一到便可能淹没数县。','城门外的灾民越来越多，粥棚已经见底。','契约的利润足够诱人，却夹着一条模糊的附约。','盐铁司的人正在逐户盘查，商人们不敢说实话。','风浪未平，船夫正等你决定先救人还是先救货。','商道若开，会带来财富，也会带来失控的武器。','药铺门前排满病人，囤货者已开始抬价。','两份请愿书同时送到，资金却只能救一处。','焦黑的街道上，店主们正等一个能继续活下去的办法。','新税令明日颁行，贫户与富户都在揣测你的立场。']
};
const OPTION_VARIANTS={
 power:[['请{n}以全局为先，先拆解各方的真正意图。','请{n}带着可信的人去核验线索，宁可慢一步也不冤枉人。','请{n}先稳住场面，再为你争取公开说话的机会。'],['请{n}在明处周旋，你则保留最后的裁断。','请{n}从旧案入手，找出能改变局势的证据。','请{n}布下反制之策，让对手先露出破绽。'],['请{n}代你传递条件，试探对方的底线。','请{n}守住要害位置，避免局势再度失控。','请{n}查明命令来源，再决定是否执行。'],['请{n}先安抚众人，把冲突拖到更有利的时机。','请{n}以自己的名义承担风险，换取一线主动。','请{n}暗中联络可靠盟友，给这局棋加一枚后手。']],
 love:[['向{n}坦言你的顾虑，请他（她）陪你把误会说开。','先听{n}把话说完，不用追问逼迫对方表态。','把最真实的担忧交给{n}，请他（她）替你守住秘密。'],['请{n}陪你去面对当事人，不让任何人独自承受。','相信{n}的判断，给彼此一次重新理解的机会。','在危局前先护住{n}，其余的事等活下来再说。'],['与{n}共同查明流言来源，用事实替代猜疑。','把旧物交给{n}，请他（她）讲完那段往事。','不强留{n}，只许下一个可以回来的约定。'],['替{n}挡下旁人的目光，再慢慢商量下一步。','向{n}伸出手，告诉他（她）这次你不会离开。','请{n}做你最诚实的提醒者，不必只说好听的话。']],
 money:[['请{n}先算清民生与成本，拟一份能落地的方案。','请{n}带人核实账目和货单，堵住可能的漏洞。','请{n}同商户谈判，把短利换成长期的承诺。'],['让{n}先安排人手与路线，保住最急需的物资。','请{n}公开账目，宁可得罪人也不留暗账。','请{n}先安置受困的人，再计算损失。'],['让{n}评估契约中的风险，改掉不公平的条款。','请{n}联络可靠商号，把资源分到最需要的地方。','请{n}守住底线，拒绝来路不明的暴利。'],['请{n}提出折中方案，既保住生意也不伤民心。','让{n}查清背后是谁在操纵价格与消息。','请{n}以自己的专长补上缺口，再决定是否投入。']]
};
const GENERIC_BANK={
 power:['边境传来急报，朝中各方都在等你表态。','一封来历不明的密信送到案前，其中藏着改变局势的线索。','两国使团在议事厅僵持不下，下一句话可能引发冲突。','有人在城中散布谣言，百姓与官员都开始不安。','你发现盟友隐瞒了一件关键信息。','一份军令与自己的判断相悖，你必须立刻决断。','敌方使者私下提出一桩危险交易。','朝堂上出现了针对你的弹劾。','旧案卷宗重见天日，牵出许多人的秘密。','城门将闭，一位重要人物仍未归来。','两支军队在边境对峙，谁都不愿先退。','你得到一枚不明来历的令牌。','政敌想借宴席试探你的立场。','城中发生刺杀，所有证据都指向错误的人。','将领与文官在军费上争执不休。','盟约即将到期，是否续约无人敢先开口。','你发现有人伪造了调兵文书。','新政推行受阻，民间怨言四起。','一位旧友请求你在关键时刻站队。','黎明前传来密报，城防出现空隙。'],
 love:['雨夜里，你遇见一位心事重重的同伴。','庆功宴散去后，有人独自留在灯下。','流言传到耳中，你需要决定是否解释。','一封未署名的信，让旧日误会重新浮现。','有人为救陌生人而冒险，你看见了这一幕。','同行途中突逢风雪，彼此只能相互依靠。','旧物被送回，勾起一段无人提及的往事。','有人在众人面前受了委屈。','临别前，对方只留下一个没有答案的问题。','一场误会使朋友之间的信任摇摇欲坠。','有人在病中仍牵挂着别人的安危。','热闹的市集里，一位同伴忽然走失。','你发现有人一直暗中替你挡下麻烦。','月下长谈时，对方说起从未示人的恐惧。','争执过后，谁也不愿先开口。','一件小礼物被悄悄放在你的门前。','有人因故乡的消息而彻夜未眠。','危局中，有人把后背交给了你。','旧日的承诺与眼前的选择发生冲突。','大局暂定后，终于有机会说出真心话。'],
 money:['城中粮价波动，百姓的生计成了难题。','一条新商路出现，但其中藏着风险。','赈灾银的账册出了缺口。','有商人愿意出资，却提出苛刻条件。','边关需要物资，运输路线迟迟定不下来。','一批珍贵货物被扣在关外。','市集即将举办大集会，各方都想从中获利。','一处矿产的归属引起争端。','工坊停工，许多工匠失去生计。','有人发现了可救急的粮仓。','修建水利需要一笔巨额资金。','灾民涌入城中，安置费用无从着落。','一份利润丰厚的契约摆在你面前。','官府要清查盐铁，商户人人自危。','船队遭遇风浪，货物与人命只能优先其一。','有人提出以秘密商道换取利益。','药材短缺，是否该控制价格成为难题。','书院与医馆同时来求资助。','一场火灾毁了半条街的店铺。','国库吃紧，新的税令即将颁布。']
};
localStorage.removeItem('dream-session');
const app=document.querySelector('#app'); let session=null, room=null, poller=null, view='home', game={queue:[],index:0,affection:{},loyalty:{}};
const api=async(path,body)=>{const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw new Error(`服务器暂时不可用（HTTP ${r.status}）。请稍后重试`)}if(!r.ok)throw new Error(data.error||'请求失败');return data};
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const shell=(body,step='剧本集')=>app.innerHTML=`<div class="game"><header class="topbar"><div class="brand">梦回·群星录</div><div>${step}</div></header>${body}</div>`;
const saveSession=()=>{};
const activateSession=()=>{clearInterval(poller);poller=setInterval(refresh,2500)};
function introPage(){clearInterval(poller);shell(`<section class="splash screen intro-screen"><div class="splash-copy"><p class="eyebrow">大夏末年 · 沧澜关前</p><h1>梦回<span>·</span>群星录</h1><p class="subtitle">与友共赴，改写青史</p><div class="seal-line"></div><p class="intro intro-long">欢迎来到《我和我的朋友们穿越到古代》！<br>这是一个专为你和你的朋友们（最多10人）打造的沉浸式古风角色扮演与叙事生成器。<br>在这里，你们将魂穿乱世，分别扮演南北两国中手握命运的关键人物。是成为权倾朝野的谋士，还是逐鹿天下的枭雄？是谱写一曲荡气回肠的绝恋，还是富可敌国搅动风云？<br>你们将共同经历一个充满变数的时代。游戏将根据你们在【权谋】、【情感】、【金钱】三条主线中的选择，计算你们与12位核心NPC的好感度与忠诚度。当所有选择尘埃落定，系统将融合所有人的命运轨迹，为你们生成一部独一无二、专属于你们的群像古风小说。<br><strong>注意：</strong>本游戏为多人协作体验，请等待所有玩家完成选择，共同揭晓属于你们的史诗结局。</p><button class="primary" data-action="intro-confirm">确认穿越 <i>→</i></button></div></section>`,'序章 · 入梦')}
function home(){view='home';clearInterval(poller);shell(`<section class="stage points-panel"><p class="section-kicker">多人叙事剧本</p><div class="heading"><div><h2>梦回·群星录</h2></div><p>2 - 10 人协作</p></div><p class="lore">一人创建剧本，朋友凭邀请码加入。所有人选择身份、分配命数，待全员完成后共同揭晓群像史书。</p><label class="track"><span>你的名字<small>将显示在房间成员中</small></span><input id="name" maxlength="16" value="${session?.name||''}" placeholder="输入名字"><b></b></label><div class="share-row"><button class="primary" data-action="create">创建剧本</button><button class="secondary" data-action="join">加入剧本</button></div><div id="join-box" hidden class="lore"><input id="code" maxlength="6" placeholder="邀请码，例如 A1B2C3"><button class="primary" data-action="confirm-join">确认加入</button></div></section>`,'序章 · 入梦')}
function npcPage(){view='npcs';shell(`<section class="stage"><div class="heading"><div><p class="section-kicker">人物图鉴</p><h2>十二位风云人物</h2></div><p>他们只能了解，不能选择。</p></div><div class="role-grid">${NPCS.map((n,i)=>`<article class="role"><span class="role-num">${String(i+1).padStart(2,'0')}</span><span class="tag">${n[1]}</span><h3>${n[0]}</h3><p>${n[2]}</p><p class="npc-skill">${n[3]}</p></article>`).join('')}</div><div class="bottom-action"><span class="hint">初始好感与忠诚均为 0</span><button class="primary" data-action="assistants">选择三名助力 <i>→</i></button></div></section>`,'卷一 · 识人')}
function assistantsPage(){view='assistants';let mine=room.players.find(p=>p.id===session.playerId),picks=mine.assistants||[];shell(`<section class="stage"><div class="heading"><div><p class="section-kicker">同行助力</p><h2>选择三名 NPC 助力</h2></div><p>他们会进入你的选项、关系网与结局。</p></div><div class="role-grid">${NPCS.map((n,i)=>`<button class="role ${picks.includes(i)?'selected':''}" data-assistant="${i}" ${!picks.includes(i)&&picks.length>=3?'disabled':''}><span class="role-num">${String(i+1).padStart(2,'0')}</span><span class="tag">${n[1]}</span><h3>${n[0]}</h3><p>${n[2]}</p><p class="npc-skill">${n[3]}</p></button>`).join('')}</div><div class="bottom-action"><span class="hint">已选择 ${picks.length} / 3 名助力</span><button class="primary" data-action="confirm-assistants" ${picks.length!==3?'disabled':''}>确认助力 <i>→</i></button></div></section>`,'卷二 · 同行')}
function rolesPage(){view='roles';let taken=new Set(room.players.filter(p=>p.id!==session.playerId).map(p=>p.role));let mine=room.players.find(p=>p.id===session.playerId);shell(`<section class="stage"><div class="heading"><div><p class="section-kicker">玩家身份</p><h2>点亮你的身份</h2></div><p>先到先得，已选身份不可重复。</p></div><div class="role-grid">${ROLES.map((r,i)=>`<button class="role ${mine.role===i?'selected':''}" data-role="${i}" ${taken.has(i)?'disabled':''}><span class="role-num">${String(i+1).padStart(2,'0')}</span><span class="tag">${r[1]}</span><h3>${r[0]}</h3><p>${taken.has(i)?'已被其他玩家选择':r[2]}</p></button>`).join('')}</div><div class="bottom-action"><span class="hint">${mine.role==null?'请选择一个身份':`已选：${ROLES[mine.role][0]}`}</span><button class="primary" data-action="points" ${mine.role==null?'disabled':''}>确认身份 <i>→</i></button></div></section>`,'卷二 · 定身')}
function pointsPage(){view='points';let mine=room.players.find(p=>p.id===session.playerId), p=mine.points||{power:0,love:0,money:0}, total=p.power+p.love+p.money;shell(`<section class="stage points-panel"><p class="section-kicker">命数分配</p><div class="heading"><div><h2>二十点，三条支线</h2></div><p>每点对应一道题</p></div><p class="lore">题目会从各支线的 20 道题库中随机抽取，绝不重复。完成顺序固定为：权谋、情感、金钱。</p>${[['power','权谋','权力、站队、战争'],['love','情感','爱情、友情、羁绊'],['money','金钱','贸易、民生、基建']].map(([k,n,d])=>`<label class="track"><span>${n}<small>${d}</small></span><input type="number" min="0" max="20" value="${p[k]}" data-point="${k}"><b>${p[k]} 题</b></label>`).join('')}<div class="bottom-action"><span class="points-total">剩余 ${20-total} 点</span><button class="primary" data-action="ready" ${total!==20?'disabled':''}>准备完毕 <i>→</i></button></div></section>`,'卷三 · 命数')}
function lobby(){view='lobby';let mine=room.players.find(p=>p.id===session.playerId), setup=room.status==='setup', enoughPlayers=room.players.length>=2;shell(`<section class="stage points-panel"><p class="section-kicker">剧本邀请码</p><div class="heading"><div><h2>${room.code}</h2></div><button class="secondary" data-action="copy">复制邀请码</button></div><p class="lore">${setup?'剧本已开启。请依次查看 NPC 图鉴、选择身份并分配技能点；所有成员准备后会自动进入答题。':'将邀请码发给朋友。至少两名玩家加入后，房主可开启剧本。'}</p><div class="relations">${room.players.map(p=>`<div class="relation"><strong>${esc(p.name)} ${p.id===room.hostId?'（房主）':''}</strong><span>${setup?(p.role==null?'尚未选择身份':ROLES[p.role][0])+' · '+(p.ready?'已准备':'未准备'):'等待房主开启'}</span></div>`).join('')}</div><div class="share-row">${setup?(mine.ready?'<button class="secondary" disabled>等待其他玩家准备</button>':`<button class="primary" data-action="npcs">查看 NPC 图鉴 <i>→</i></button>`):''}${!setup&&session.playerId===room.hostId?`<button class="primary" data-action="start" ${enoughPlayers?'':'disabled'}>开启剧本 <i>→</i></button>`:''}</div></section>`,'剧本房间')}
function shuffled(items,seed){let a=[...items], n=seed.split('').reduce((x,c)=>x+c.charCodeAt(0),0);for(let i=a.length-1;i>0;i--){n=(n*9301+49297)%233280;let j=n%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function relationshipDelta(line,name,taskIndex){let skill=NPC_SKILL[name]?.[line]||8,match=(TASK_MATCH[line][taskIndex]||[]).includes(name),variance=(taskIndex%4)-1,score=skill+(match?6:0)+variance;if(score>=24)return line==='love'?[25,16]:line==='power'?[17,25]:[22,19];if(score>=19)return line==='love'?[21,13]:line==='power'?[15,22]:[20,14];if(score>=15)return line==='love'?[14,10]:line==='power'?[10,16]:[13,11];if(score>=12)return line==='love'?[10,6]:line==='power'?[8,11]:[10,7];return line==='love'?[-15,-5]:line==='power'?[-10,-15]:[-12,-7]}
function buildGame(){let mine=room.players.find(x=>x.id===session.playerId),p=mine.points,assistants=mine.assistants.map(i=>({id:i,name:NPCS[i][0]}));game={queue:[],index:0,affection:{},loyalty:{},assistants};['power','love','money'].forEach(line=>shuffled(GENERIC_BANK[line].map((text,taskIndex)=>({text,taskIndex})),room.code+line).slice(0,p[line]).forEach(question=>game.queue.push({line,...question})));eventPage()}
function optionText(line,name,index,taskIndex){let template=OPTION_BANK[line][taskIndex%OPTION_BANK[line].length][index];return template.replaceAll('{n}',name)}
function eventPage(){let item=game.queue[game.index];if(!item)return finishGame();let {line,text,taskIndex}=item,labels={power:'权谋支线',love:'情感支线',money:'金钱支线'},options=game.assistants.map((n,i)=>optionText(line,n.name,i,taskIndex));shell(`<section class="stage event-layout"><div class="progress">${game.queue.map((x,i)=>`<i class="${i<game.index?'done':''} ${x.line===line?'active':''}"></i>`).join('')}</div><div class="event-type">${labels[line]} · ${game.index+1} / ${game.queue.length}</div><article class="event-card"><p class="section-kicker">事件需求：${(TASK_MATCH[line][taskIndex]||[]).join(' / ')} 擅长</p><h2>${text}</h2>${options.map((c,i)=>`<button class="choice" data-choice="${i}"><b>${'ABC'[i]}</b>${c}</button>`).join('')}<div class="impact" id="impact"></div></article></section>`,'卷四 · 抉择');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=async()=>{let index=+b.dataset.choice,n=game.assistants[index],t=n.name,[a,l]=relationshipDelta(line,t,taskIndex);game.affection[t]=(game.affection[t]||0)+a;game.loyalty[t]=(game.loyalty[t]||0)+l;document.querySelector('#impact').textContent=`${t}：好感 ${a>0?'+':''}${a}，忠诚 ${l>0?'+':''}${l}`;await api('/api/answer',{...session,answer:{line,target:t,index,taskIndex},affection:game.affection,loyalty:game.loyalty});game.index++;setTimeout(eventPage,500)})}
async function finishGame(){await api('/api/finish',session);game.queue=[];await refresh()}
function relationship(player,name){let a=player.affection?.[name]||0,l=player.loyalty?.[name]||0;if(a>=100&&l>=100)return '命定同盟';if(a>=100)return '情深不渝';if(l>=100)return '生死追随';if(a>=80&&l>=80)return '生死羁绊';if(a>=80)return '倾心相守';if(l>=80)return '誓约追随';if(a>=60&&l>=60)return '肝胆相照';if(a>=60)return '心意相通';if(l>=60)return '忠诚同袍';if(a>=45||l>=45)return '并肩知己';if(a>=20||l>=20)return '可靠伙伴';return '同行助力'}
function relationTotal(player){return (player.assistants||[]).reduce((sum,i)=>{let n=NPCS[i][0];return sum+(player.affection?.[n]||0)+(player.loyalty?.[n]||0)},0)}
function ending(player){let names=(player.assistants||[]).map(i=>NPCS[i][0]),total=relationTotal(player),top=names.sort((a,b)=>(player.affection?.[b]||0)+(player.loyalty?.[b]||0)-(player.affection?.[a]||0)-(player.loyalty?.[a]||0))[0]||'无人';if(total>=800)return ['金銮明辉',`你以三名助力的信任为刃，穿过夺嫡血雨，最终成为左右新朝的人。${top}始终站在你的棋局之内，而另外两人替你守住了天下的退路。`];if(total>=680)return ['凤仪天下',`你没有被任何一方的权势吞没，而是借三名助力的声望与忠诚重写秩序。${top}陪你登上最高的台阶，旧日的敌手也在新法下低头。`];if(total>=540)return ['铁血丹心',`边关风雪中，你与${top}并肩守住最后一道防线。三名助力把各自的长处交给你，令一场将要倾覆的战事有了转机。`];if(total>=420)return ['人间知己',`你在乱世中守住了人与人之间的信任，${top}最终成为最懂得你的人。三段关系没有被权力磨损，反而在每次选择后更坚固。`];if(total>=300)return ['富甲天下',`你将三名助力带来的消息、商路与人脉织成一张网，让粮道与市集重新流动。${top}见证了万家灯火再次点亮。`];if(total>=190)return ['江湖浪子',`你不愿把余生交给朝堂，于是带着三名助力留下的信物远走江湖。${top}偶尔寄来书信，提醒你仍有人记得那段同行。`];if(total>=90)return ['归隐山林',`你厌倦了史书上的喧嚣，带着与三名助力共同经历过的故事退入山林。${top}偶尔来访，炉火旁仍能谈起沧澜关的旧雪。`];return ['平淡一生',`你没有成为改变天下的名字，却与三名助力保持着淡淡的联系。乱世远去后，你在寻常日子里守住了自己的小小安稳。`]}
function finalPage(){let players=room.players,mine=players.find(p=>p.id===session.playerId),[title,desc]=ending(mine),names=(mine.assistants||[]).map(i=>NPCS[i][0]),relations=names.map(n=>`${n}：${relationship(mine,n)}（好感 ${mine.affection?.[n]||0}，忠诚 ${mine.loyalty?.[n]||0}）`),lead=names[0]||'沧澜关',second=names[1]||'金陵',third=names[2]||'天京',all=players.map(p=>{let [t,d]=ending(p);return `【${esc(p.name)} · ${t}】${d}`}).join('\n\n'),story=`《梦回·群星录》\n\n楔子：沧澜关的风卷起南北旌旗，${ROLES[mine.role][0]}与同伴们带着现代记忆，在大夏末年的停战之盟中醒来。谁也不知道，一张互市文书会将他们推向夺嫡、兵乱与人心的漩涡。\n\n第一卷：沧澜之盟\n最初的选择落在一封密信与一声号角之间。你没有独自走进局中：${lead}替你照见暗处的锋芒，${second}在众目睽睽下替你稳住局面，${third}则为你留下了退路。三人的心意因你的决定而涨落，命运也开始有了不同的走向。\n\n第二卷：金陵暗流\n权谋、情感与财货三条道路在金陵与天京交错。你曾在朝堂上按住将要拔出的剑，也曾在夜雨中听完未能说出口的旧事；当粮价飞涨、民心不安时，你明白真正能改变天下的，并不只是一纸诏令。\n\n第三卷：群星入局\n局势最危急的一夜，三名助力终于各自作出选择。有人替你守住城门，有人带来决定胜负的消息，有人将最后的筹码交到你手中。你也用一次次回应告诉他们：在这乱世里，信任并非软弱，而是比刀兵更难得到的力量。\n\n终卷：${title}\n${desc}。春日再临沧澜关时，旧日烽火已远，史官将你的名字写在新篇开端，而那三名始终与你同行的人，也被写进了同一页。\n\n你的三名助力与最终关系\n${relations.join('\n')}\n\n史书列传\n${all}`;shell(`<section class="stage results"><div class="scroll-title"><p class="section-kicker">全员归位 · 千秋史笔</p><h2>${title}</h2><p>${desc}</p></div><article class="ending"><h3>你的三名助力</h3><p>${relations.join('；')}</p></article><article class="history" id="story">${story}</article><div class="share-row"><button class="primary" data-action="download">下载群像史书</button><button class="secondary" data-action="leave">离开剧本</button></div></section>`,'终卷 · 千秋史笔')}
function waiting(){shell(`<section class="stage points-panel"><p class="section-kicker">书卷封印中</p><div class="heading"><div><h2>待众友归位</h2></div><p>${room.players.filter(p=>p.finished).length} / ${room.players.length} 完成</p></div><p class="lore">你的选择已写入史书。请等待其他玩家完成所有题目，群像结局将自动揭晓。</p></section>`,'卷末 · 等待')}
async function refresh(){if(!session)return home();try{let latest=await api(`/api/room?code=${session.code}`);if(latest.status==='playing'){room=latest;let mine=room.players.find(p=>p.id===session.playerId);if(mine.finished)waiting();else if(!game.queue.length)buildGame()}else if(latest.status==='finished'){room=latest;finalPage()}else if(view==='lobby'){room=latest;lobby()}}catch(e){localStorage.removeItem('dream-session');session=null;home()}}
async function create(){let name=(document.querySelector('#name')?.value||'').trim()||'房主';let data=await api('/api/create',{name});session={...data,name};saveSession();view='lobby';await refresh();activateSession()}
async function join(){let name=document.querySelector('#name').value.trim(),code=document.querySelector('#code').value.trim();if(!name||!code)return alert('请输入名字与邀请码');let data=await api('/api/join',{name,code});session={...data,name};saveSession();view='lobby';await refresh();activateSession()}
app.addEventListener('click',async e=>{let action=e.target.closest('[data-action]')?.dataset.action,role=e.target.closest('[data-role]')?.dataset.role,assistant=e.target.closest('[data-assistant]')?.dataset.assistant;try{if(action==='intro-confirm'){home();return}if(assistant!==undefined){let mine=room.players.find(p=>p.id===session.playerId),id=+assistant,picks=mine.assistants||[];mine.assistants=picks.includes(id)?picks.filter(x=>x!==id):[...picks,id];assistantsPage()}if(role!==undefined){room=await api('/api/role',{...session,role:+role});rolesPage()}if(action==='create')await create();if(action==='join')document.querySelector('#join-box').hidden=false;if(action==='confirm-join')await join();if(action==='copy')navigator.clipboard?.writeText(room.code);if(action==='npcs')npcPage();if(action==='assistants')assistantsPage();if(action==='confirm-assistants'){let mine=room.players.find(p=>p.id===session.playerId);room=await api('/api/assistants',{...session,assistants:mine.assistants});rolesPage()}if(action==='roles')rolesPage();if(action==='points')pointsPage();if(action==='ready'){let p={};document.querySelectorAll('[data-point]').forEach(i=>p[i.dataset.point]=+i.value||0);room=await api('/api/ready',{...session,points:p});if(room.status==='playing')buildGame();else lobby()}if(action==='start'){room=await api('/api/start',session);lobby()}if(action==='download'){let u=URL.createObjectURL(new Blob([document.querySelector('#story').innerText],{type:'text/plain'})),a=document.createElement('a');a.href=u;a.download='梦回群星录-群像史书.md';a.click();URL.revokeObjectURL(u)}if(action==='leave'){session=null;room=null;game={queue:[],index:0,affection:{},loyalty:{}};introPage()}}catch(err){alert(err.message)}});
app.addEventListener('input',e=>{if(e.target.dataset.point){let inputs=[...document.querySelectorAll('[data-point]')],total=inputs.reduce((n,i)=>n+(+i.value||0),0);e.target.nextElementSibling.textContent=`${e.target.value||0} 题`;document.querySelector('.points-total').textContent=`剩余 ${20-total} 点`;document.querySelector('[data-action="ready"]').disabled=total!==20}});
if(session){view='lobby';refresh();poller=setInterval(refresh,2500)}else introPage();
